version: '3.8'

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    volumes:
      - ./etcd/data:/bitnami/etcd
    restart: always

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    restart: always
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8080:8080"
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/data:/home/nacos/data
    env_file:
      - .env
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m

  apisix:
    image: apache/apisix:latest
    container_name: apisix
    restart: always
    ports:
      - "9080:9080"
      - "9443:9443"
      - "9180:9180"
    volumes:
      - ./apisix/config/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix/plugin/jwks-auth.lua:/usr/local/apisix/apisix/plugins/jwks-auth.lua
    env_file:
      - .env
    depends_on:
      - nacos
      - etcd

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
